module:
  _target_: src.models.base_model.BaseModel

f_func:
  _target_: src.networks.mlp.MLPEmbedConcat
  hidden_shapes: [64,64,64]
  t_hidden_shapes: [64,64]
  x_hidden_shapes: [64,64]
  t_emb_dim: 64
  x_emb_dim: 64

g_func:
  _target_: src.networks.simple.IdentityOne

sde_model:
  _target_: src.models.pis_nn.PISNN
  reg_fns:
    - src.models.loss.quad_reg
  f_format: "t_tnet_grad"
  data_shape: ${model.data_shape}
  sigma: ${sigma}
  sde_type: ito
  nn_clip: 1e4
  lgv_clip: 1e4

sdeint:
  _target_: torchsde.sdeint
  method: euler

lr: ${lr}
weight_decay: 1e-7


data_ndim: ${datamodule.ndim}
data_shape: ${datamodule.shape}
num_steps: ${num_steps}
t_end: ${t_f}
