# https://wandb.ai

wandb:
  # _target_: src.logger.wandb_logger.WandbLogger
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "PIS_benchmark"
  name: ${hydra:job.override_dirname}
  group: ${group}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  entity: "oxcsml"  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  tags: []
