# @package _global_

defaults:
  - base
  - override /hydra/launcher: submitit_slurm

n_jobs: 8
num_gpus: 1

hydra:
  # job:
  #   env_set:
  #     WANDB_API_KEY: # include API key for logging in to wandb
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 2880
    cpus_per_task: ${num_gpus}
    tasks_per_node: 1
    mem_gb: 15
    name: ${hydra.job.name}
    partition: high-bigbayes-gpu
    max_num_timeout: 0
    array_parallelism: ${n_jobs}
    setup: ["export XLA_FLAGS='--xla_gpu_cuda_data_dir=/opt/cuda'", "export PATH=/opt/cuda/bin/:$PATH", "export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH", "export XLA_PYTHON_CLIENT_PREALLOCATE=false"]
    # setup: ["export XLA_PYTHON_CLIENT_PREALLOCATE=false"]
    # executable: /data/ziz/not-backed-up/${oc.env:USER}/miniconda3/envs/diffusion-smc/bin/python
    additional_parameters: {
      "clusters": "srf_gpu_01",
      "wckey": "wck_${oc.env:USER}",
      "gres": "gpu:${num_gpus}",
      # "nodelist": "zizgpu05.cpu.stats.ox.ac.uk"
      # "exclude": "zizgpu05.cpu.stats.ox.ac.uk"
    }
