defaults:
  - datamodule

dataset:
  _target_: src.datamodules.datasets.difficult_gaussian.DifficultGaussian
  mean: 2.75
  scale: 0.25
  len_data: 15000
  dim: 1

ndim: ${datamodule.dataset.dim}
shape: ${datamodule.dataset.dim}
