defaults:
  - datamodule

dataset:
  _target_: src.datamodules.datasets.cox.CoxDist
  len_data: 15000
  dim: 1600
  path: /vols/ziz/not-backed-up/anphilli/pis/data/fpines.csv

ndim: ${datamodule.dataset.dim}
shape: ${datamodule.dataset.dim}
